#!/usr/bin/env bash
# comment
{
    grep -v 'localhost' /etc/hosts | grep -v 'facebook.com'
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
} > /tmp/hosts.tmp
cp /tmp/hosts.tmp /etc/hosts
rm /tmp/hosts.tmp
